# Reference: https://docs.gradle.org/current/userguide/platforms.html


[versions]
kotlin = "1.9.10"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
release = { id = "io.cloudshiftdev.release", version = "0.2.4" }
nexusPublish = { id = "io.github.gradle-nexus.publish-plugin", version = "2.0.0-rc-1" }

[libraries]

### Testing libraries
#
#

# JUnit
junit-bom = { module = "org.junit:junit-bom", version = "5.10.0" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }

# Kotest
kotest-bom = { module = "io.kotest:kotest-bom", version = "5.6.2" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core" }
kotest-assertions-json = { module = "io.kotest:kotest-assertions-json" }
kotest-framework-datatest = { module = "io.kotest:kotest-framework-datatest" }
kotest-property = { module = "io.kotest:kotest-property" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5" }
kotest-extensions-spring = { module = "io.kotest.extensions:kotest-extensions-spring", version = "1.1.3" }

#
### General libraries
#
#

asm-bom = { module = "org.ow2.asm:asm-bom", version = "9.5" }
asm-core = { module = "org.ow2.asm:asm" }
asm-tree = { module = "org.ow2.asm:asm-tree" }
asm-util = { module = "org.ow2.asm:asm-util" }

caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version = "3.1.8" }
aspectj-tools = { module = "org.aspectj:aspectjtools", version = "1.9.20" }

guava = { module = "com.google.guava:guava", version = "32.1.2-jre" }
awscdk = { module = "software.amazon.awscdk:aws-cdk-lib", version = "2.93.0" }
squareup-kotlinpoet = { module = "com.squareup:kotlinpoet", version = "1.14.2" }
javaparser-core = { module = "com.github.javaparser:javaparser-core", version = "3.25.4" }
